### ISSUE TITLE
tuningbug

### ISSUE THREAD

**Issue by DorteY** [raydNDev/BerkshireCountyReloaded#1]
wenn man im tuningshop mehrere sachen anklickt & davon eins kauft, hat man automatisch alle gekauft, die man angeklickt hat

**Comment by raydNDev** [comment]
Vielen Dank für deine Meldung,
ich werde mich schnellstmöglich um die Behebung des Fehlers kümmern.

**Comment by raydNDev** [comment]
Ist gefixt.
